theme: jekyll-theme-cayman
title: Yet, an other portfolio
description: A portfolio from a random guy named Antoine
show_downloads: false

social:
  name: Antoine BERNARD
  links:
    - https://www.linkedin.com/in/aberna
    - https://github.com/LittleDuckSugar

collections:
  authors:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

link:
  linkedin: https://www.linkedin.com/in/aberna/
  github: https://github.com/LittleDuckSugar