theme: jekyll-theme-cayman
title: Yet, an other portfolio
description: A portfolio from a random guy named Antoine
show_downloads: false

link:
  linkedin: https://www.linkedin.com/in/aberna/
  github: https://www.github.com/LittleDuckSugar